### ISSUE TITLE
python script only in terminal ?

### ISSUE THREAD

**Issue by tissatussa** [AnshGaikwad/Chess-World#6]
hi, i just discovered your python script that plays chess, by reading the article "Let’s create a Chess AI" at https://medium.com/dscvitpune/lets-create-a-chess-ai-8542a12afef .. i copied the code and i followed the instructions .. indeed, it plays chess in my webbrowser!

Your python script seems nice and basic! Now i want to adjust it to only work in terminal, not using a webbrowser .. i think i will succeed, but maybe you already made such version ? It could even have an UCI protocol, so the engine can play in CuteChess against other engines ?

**Comment by tissatussa** [comment]
It plays stubborn .. here's my first game .. i should have won, nevermind :

```
[Event "human vs engine"]
[Site "Holland @ https://lichess.org/BcpIKJGj "]
[Date "2022.10.12"]
[Round "?"]
[White "Roelof Berkepeis"]
[Black "Chess-World AI"]
[Result "0-1"]

1.Nf3 Nf6 2.g3 Nc6 3.d4 e6 4.Bg2 d5 5.O-O Bd6 6.b3 Bd7 7.Bb2 Qe7 8.a3 Rd8 9.c4 dxc4 10.bxc4 Bc8 11.Qa4 Qd7 12.Bh3 Ne5 13.Qxd7+ Nexd7 14.Nbd2 O-O 15. e4 Be7 16.Bc3 Nb6 17.a4 Rfe8 18.e5 Nfd7 19.a5 Na8 20.Ne4 f5 21.exf6 Nxf6 22.Neg5 Rd6 23.Rfe1 Rc6 24.Ne5 Ra6 25.f4 c5 26.Ngf3 cxd4 27.Nxd4 Nc7 28. Kh1 Bc5 29.Nb3 Bf8 30.Rad1 Be7 31.Bg2 Bf8 32.Rd2 Be7 33.Red1 Rf8 34.g4 Nfe8 35.Rf1 Nd6 36.Ra2 Nde8 37.Bd4 b6 38.Nc6 Bf6 39.Be5 bxa5 40.Nc5 Rxc6 41.Bxf6 Rxc5 42.Be7 Rxc4 43.Bxf8 Kxf8 44.Rxa5 a6 {And i gave up.} 0-1
```

Note: in this position Black used about 50 (!) minutes to decide 8...Ra8-d8 :

![Black calculated more than 15 minutes to play Ra8-d8](https://user-images.githubusercontent.com/1109281/195339253-2d4a9035-f1f8-47e8-9a3a-7f391c9c8de3.png)

but most other moves were done much quicker.

**Comment by AnshGaikwad** [comment]
Hi @tissatussa, apologies for the late reply. Thanks for trying out our code. Yes, we did have the terminal-based code but didn't get to check it in. 

50 minutes! That's strange, we will need to study the computations made by the AI and see what consumed much time. Thanks for letting us know. 😊
